<template lang="html">
  <div class="">
    <img src="https://wallpapercave.com/wp/wp1975763.jpg" alt="" style="width:70%; margin: 4.5% 0 0 -50%; position:fixed;">
    <div class="row" style="position:fixed; margin: 5% 0 0 30%; width: 65%;">
      <div class="col s12 m12 slide-fwd-bottom">
        <div class="card white lighten-3 large">
          <div class="card grey lighten-1">
          <span class="card-title"> <b>Add new article</b> </span>
          </div>
          <div class="card-content" style="margin-bottom:40%;">
            <div class="input-field col s12">
              <input id="title" type="text" class="validate" v-model='title'>
              <label for="title">Title</label>
            </div>
            <label>Article:</label>
            <div class="input-field col s12">
              <Vueditor ref="editor" style="position:static;"></Vueditor>
            </div>
          </div>
          <div class="card-action">
            <div class="row" style="margin: 0 0 1% 0;">
              <div class="col s12">
                <div class="col s6">
                  <a class="btn btn-block center grey darken-4" style="margin: 2% 2% 0 0; width:100%;" @click='post'>Post</a>
                </div>
                <div class="col s6">
                  <a class="btn btn-block center grey darken-4" style="margin: 2% 2% 0 0; width:100%;" @click='cancel'>Cancel</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'
import Vueditor from 'vueditor'

export default {
  data () {
    return {
      title: ''
    }
  },
  component : {
    Vueditor
  },
  methods: {
    cancel () {
      this.$router.push('/')
    },
    post () {
      const token = localStorage.getItem('authorization').split('*#$_.')[0]
      const article = this.$refs.editor.getContent()

      const articleData = {
        title: this.title,
        article: article
      }

      axios({
        method: 'post',
        url: 'http://35.240.155.222/article',
        data: {
          token: token,
          article: articleData
        }
      }).then(response => {
        this.$refs.editor.setContent('')
        this.title = ''
        this.$router.push('/')
      }).catch(err => {
        console.log(err);
      })
    }
  }
}
</script>

<style lang="css">
.slide-fwd-bottom {
  -webkit-animation: slide-fwd-bottom 0.45s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
          animation: slide-fwd-bottom 0.45s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-2 19:13:53
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-fwd-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-fwd-bottom {
  0% {
    -webkit-transform: translateZ(0) translateY(-110%);
            transform: translateZ(0) translateY(-110%);
  }
  100% {
    -webkit-transform: translateZ(160px) translateY(-10%);
            transform: translateZ(160px) translateY(0px);
  }
}
@keyframes slide-fwd-bottom {
  0% {
    -webkit-transform: translateZ(0) translateY(-110%);
            transform: translateZ(0) translateY(-110%);
  }
  100% {
    -webkit-transform: translateZ(160px) translateY(-10%);
            transform: translateZ(160px) translateY(0px);
  }
}
</style>
