<template lang="html">
  <nav class="white slide-fwd-bottom" style="position:fixed; margin: 0% 50% 0 0;">
    <div class="nav-wrapper">
      <img class="brand-logo left" src="@/assets/153061742310103255.png" alt="" style=" margin: 0 0 0 -45%; width:10%;" >
      <a class="brand-logo left" style="margin-left:-43%; font-size:15px; cursor:pointer;" @click=''> </a>
      <!-- <ul class="right hide-on-med-and-down" style="margin: 0 5% 0 0;">
        <li @click='openLogin'><a class="waves-effect waves-dark" style="color:white; margin: 0 50% 0 -20%; width:100%;" v-if='checkToken() == true'><b>Login</b> </a></li>
        <li @click='openRegister'><a class="waves-effect waves-dark" style="color:white; margin: 0 0 0 0;" v-if='checkToken() == true'><b>Register</b> </a></li>
        <li @click='backToQuestion'><a class="waves-effect waves-dark" style="color:white" v-if='checkToken() == false'><b>Home</b> </a></li>
        <li @click='logout'><a class="waves-effect waves-dark" style="color:white; margin: 0 0 0 40%;" v-if='checkToken() == false'><b>Logout</b> </a></li>
      </ul> -->
    </div>
  </nav>
</template>

<script>
export default {
}
</script>

<style scoped>

.header {
  background-image: url("http://getwallpapers.com/wallpaper/full/0/6/4/40669.jpg");
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}

.body-background{
  text-align: left;
  height: 100%;
  width: 100%;
  background-size: cover;
  position: absolute;
}

.modal {
  overflow: hidden;
  width: 35%;
  height: 600px;
  margin-top: 0px;
  padding: 0 0 0 0;
}

.container{
	margin: 0 0 0 0;
	width: 455px;
	height: 100%;
}

.tabs .indicator
{
	background-color: #1e2121;
	opacity: 0.3;
}

.form-container
{
	padding: 40px;
	padding-top: 10px;
}

.confirmation-tabs-btn
{
	position: absolute;
}
element.style {
    z-index: 1003;
    display: block;
    opacity: 1;
    top: 1%;
}
.slide-fwd-bottom {
  -webkit-animation: slide-fwd-bottom 0.45s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
          animation: slide-fwd-bottom 0.45s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-2 19:13:53
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-fwd-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-fwd-bottom {
  0% {
    -webkit-transform: translateZ(0) translateY(-110%);
            transform: translateZ(0) translateY(-110%);
  }
  100% {
    -webkit-transform: translateZ(160px) translateY(-10%);
            transform: translateZ(160px) translateY(0px);
  }
}
@keyframes slide-fwd-bottom {
  0% {
    -webkit-transform: translateZ(0) translateY(-110%);
            transform: translateZ(0) translateY(-110%);
  }
  100% {
    -webkit-transform: translateZ(160px) translateY(-10%);
            transform: translateZ(160px) translateY(0px);
  }
}
</style>
