<template>
  <div class="body-background">
    <div class="container">
      <div id="" class="card center grey darken-4 scale-up-center" style="height: 88%; width: 125%; margin: 10% 0 0 -10%; padding: 0 0 0 0; position:static;">
        <div class="card-stacked">
          <br>
          <br>
          <img src="http://icons-for-free.com/free-icons/png/128/479477.png" alt="">
          <div class="card-content">
            <pre style="color: grey;">User Id: {{ profile._id }}</pre>
            <h3 style="color: white;">{{ profile.username }}</h3>
          </div>
          <div class="card-action">
            <div class="row" style="margin: 5% 0 0 0;">
              <div class="col s12 m12 slide-fwd-bottom" v-for='question in myArticles'>
                <div class="card grey darken-3">
                  <div class="card-content white-text">
                    <div class="row">
                      <div class="col">
                        <span class="card-title" style=" margin: 0 0 0 0;">{{ question.title }}</span>
                      </div>
                      <div class="col right" style="margin: -1% 0 0 0;">
                        <pre style="color:grey;">{{ question.date }}</pre>
                      </div>
                    </div>
                    <br>
                  </div>
                  <div class="card-action" style="text-align:right;">
                    <a class="btn card waves-effect waves-dark red darken-4" style="position:static; margin: 0 0 0 0;" @click='openDetail(question)'>Open detail</a>
                    <a class="btn card waves-effect waves-dark red darken-4" style="position:static; margin: 0 0 0 2%;" @click='edit'>Edit Question</a>
                    <a class="btn card waves-effect waves-dark red darken-4" style="position:static; margin: 0 0 0 2%;" @click='deleteDetail(question)'>Delete</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'
import Vueditor from 'vueditor'

export default {
  data () {
    return {
      myArticles: []
    }
  },
  computed : {
    profile () {
      return this.$store.state.profile
    }
  },
  created () {
    const all = this.$store.state.articles


    all.forEach(val => {
      if (val.UserId._id == this.profile._id) {
        console.log(val);
        this.myArticles.push(val)
      }
    })
  },
  methods : {
    openDetail (question) {
      if (this.isLogin == true) {
        if (this.$store.state.profile._id == question.UserId._id) {
          this.isUser = true
          this.$store.dispatch('openDetail', question)
        } else {
          this.$store.dispatch('openDetail', question)
        }
      } else {
        this.$store.dispatch('openDetail', question)
      }
    },
    deleteDetail (question) {
      // axios({
      //   method: 'delete',
      //   url: `http://35.229.80.220/question/${question._id}`
      // }).then(response => {
      //   swal({
      //     title: "Yosh!",
      //     text: `Article with title ${response.data.title} was deleted!`,
      //     icon: "success",
      //   });
      //   this.$router.push('/')
      // }).catch(err => {
      //   console.log(err);
      // })
    },
    edit () {
      // this.$router.push('edit')
    }
  }
}
</script>

<style scoped>
.body-background{
  text-align: left;
  height: 100%;
  width: 100%;
}
.scale-up-center {
	-webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-3 0:53:39
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

</style>
