<template lang="html">
  <div class="">
    <img src="https://i.pinimg.com/564x/f4/1b/a9/f41ba9be3c04a0b87dfce70c5831599a.jpg" alt="" style="width:35%; position:fixed; margin: 0 0 0 -50%;">
    <div class="slide-fwd-bottom" style="padding: 4% 0 0 0; margin: 0 0 0 25%;">
      <h4 class=""> <b>Sign Up</b> </h4>
      <div class="container" style="width:65%">
        <div class="row">
          <div class="input-field col s12">
            <input id="username" type="text" class="validate" v-model='registerData.username'>
            <label for="username">Username</label>
          </div>
          <div class="input-field col s12">
            <input id="email" type="email" class="validate" v-model='registerData.email'>
            <label for="email">Email</label>
          </div>
          <div class="input-field col s12">
            <input id="password" type="password" class="validate" v-on:keyup='checkValidation' v-model='registerData.password'>
            <label for="password">password</label>
          </div>
          <label class="left" style="margin:-2% 0 0 2%; color:red;" v-if='validation == false'>Password minimum 6 character!</label>
          <div class="input-field col s12">
            <input id="confirm" type="password" class="validate" v-on:keyup='check' v-model='registerData.confirm'>
            <label for="confirm">Confirm Password</label>
          </div>
          <label class="left" style="margin:-2% 0 0 2%; color:red;" v-if='checkPassword == false'>Password didn't match!</label>
        </div>
        <br>
        <div class="row">
          <div class="col s12">
            <div class="col s6">
              <a class="btn btn-block" @click='register'>Sign Up</a>
            </div>
            <div class="col s6">
              <a class="btn btn-block" @click='back'>Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  data () {
    return {
      registerData: {
        username: '',
        email: '',
        password: '',
        confirm: ''
      },
      checkPassword: true,
      validation: true
    }
  },
  methods: {
    back () {
      this.$router.push('/')
    },
    register () {
      if (this.validation == true && this.checkPassword == true && this.registerData.password.length != 0) {

        const register = {
          username: this.registerData.username,
          email: this.registerData.email,
          password: this.registerData.password
        }

        if (this.registerData.confirm == '') {
          this.checkPassword = false
        } else {
          axios({
            method: 'post',
            url: 'http://35.240.214.13 /users/register',
            data: register
          }).then((response) => {
            this.registerData.username = ''
            this.registerData.email = ''
            this.registerData.password = ''
            this.registerData.confirm = ''
            swal({
              title: "Yosh!",
              text: "Successfully register your account",
              icon: "success",
            });
          }).catch(err => {
            this.registerData.username = ''
            this.registerData.email=''
            this.registerData.password=''
            swal({
              text: "email is already exists",
              icon: "error",
            })
          })
        }

      } else {
        swal({
          text: "Please input a valid data . . .",
          icon: "error"
        })
      }
    },
    check () {
      if (this.registerData.password == this.registerData.confirm || this.registerData.confirm.length == 0) {
        this.checkPassword = true
      } else {
        this.checkPassword = false
      }
    },
    checkValidation () {
      if (this.registerData.password.length >= 6 || this.registerData.password.length == 0) {
        this.validation = true
      } else {
        this.validation = false
      }
    }
  }
}
</script>

<style lang="css">
.slide-fwd-bottom {
  -webkit-animation: slide-fwd-bottom 0.45s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
          animation: slide-fwd-bottom 0.45s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-7-2 19:13:53
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-fwd-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-fwd-bottom {
  0% {
    -webkit-transform: translateZ(0) translateY(-110%);
            transform: translateZ(0) translateY(-110%);
  }
  100% {
    -webkit-transform: translateZ(160px) translateY(-10%);
            transform: translateZ(160px) translateY(0px);
  }
}
@keyframes slide-fwd-bottom {
  0% {
    -webkit-transform: translateZ(0) translateY(-110%);
            transform: translateZ(0) translateY(-110%);
  }
  100% {
    -webkit-transform: translateZ(160px) translateY(-10%);
            transform: translateZ(160px) translateY(0px);
  }
}
</style>
